# Generated by Django 5.0.3 on 2024-04-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.PositiveIntegerField(choices=[(1, 'Other'), (100, 'Air Pods'), (101, 'Phone'), (102, 'Computer'), (103, 'Ipad'), (104, 'Headphones'), (105, 'Camera'), (106, 'Tablet'), (107, 'Smart Watch'), (108, 'Charger'), (300, 'Rain Jacket'), (301, 'Umbrella'), (302, 'Sunglasses'), (303, 'Coat'), (304, 'Hat'), (306, 'Gloves'), (307, 'Scarf'), (308, 'Shoes'), (400, 'Credit Card'), (401, 'Keys'), (402, 'Watch'), (403, 'Backpack'), (404, 'Purse'), (405, 'Jewelry'), (406, 'Wallet'), (407, 'Passport'), (408, 'Id'), (409, 'Glasses'), (410, 'Water Bottle'), (411, 'Book'), (412, 'Notebook'), (413, 'Pencil Case'), (414, 'Sports Equipment'), (500, 'Bicycle'), (501, 'Scooter'), (502, 'Helmet')]),
        ),
    ]
