# Generated by Django 5.0.3 on 2024-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.PositiveIntegerField(choices=[(100, 'Submitted'), (200, 'Flagged'), (300, 'Under Review'), (400, 'Approved'), (500, 'Rejected')], default=100),
        ),
    ]
