# Generated by Django 5.0.3 on 2024-04-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location_category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
