# Generated by Django 5.0.3 on 2024-03-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_picture_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
